(Pipeline(steps=[('functransformer-1', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80af980a10>), ('hashingvectorizer', HashingVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
         dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
         lowercase=True,...)), ('functransformer-2', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80d3040610>)]), Pipeline(steps=[('functransformer-1', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adb47f90>), ('hashingvectorizer', HashingVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
         dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
         lowercase=True,...)), ('functransformer-2', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adb47fd0>)]), Pipeline(steps=[('functransformer-1', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adb47e10>), ('hashingvectorizer', HashingVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
         dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
         lowercase=True,...)), ('functransformer-2', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adb47d50>)]), Pipeline(steps=[('functransformer-1', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adaec150>), ('hashingvectorizer', HashingVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
         dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
         lowercase=True,...)), ('functransformer-2', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adaec190>)]), Pipeline(steps=[('functransformer-1', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adaec910>), ('hashingvectorizer', HashingVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
         dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
         lowercase=True,...)), ('functransformer-2', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adaec950>)]), Pipeline(steps=[('functransformer-1', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adb47d90>), ('hashingvectorizer', HashingVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
         dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
         lowercase=True,...)), ('functransformer-2', <clusterix.clustering.clusters.FuncTransformer object at 0x7f80adb47c90>)]))
